<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>NCoreUtils</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NCoreUtils.Videos.WebService.Client\NCoreUtils.Videos.WebService.Client.csproj" />
  </ItemGroup>
</Project>
