<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="NCoreUtils.FFMpeg.Interop.AVRational" Alias="AVRational" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NCoreUtils.Videos.Abstractions\NCoreUtils.Videos.Abstractions.csproj" />
    <!--
    <ProjectReference Include="..\..\NCoreUtils.FFMpeg\NCoreUtils.FFMpeg\NCoreUtils.FFMpeg.csproj" />
    -->
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NCoreUtils.FFMpeg.6.1-x64" Version="8.0.0-rc01" />
  </ItemGroup>
</Project>
