<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- <TargetFrameworks>net8.0;net7.0;net6.0;netstandard2.1</TargetFrameworks> -->
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>NCoreUtils.Videos</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NCoreUtils.Extensions.Memory" Version="8.0.2" />
    <PackageReference Include="NCoreUtils.IO.Abstractions" Version="8.0.0" />
    <PackageReference Include="NCoreUtils.Resources.Abstractions" Version="8.0.1" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
    <Compile Include="..\shared\CompilerServices\**" />
  </ItemGroup>
</Project>
